name: deploy

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Generate versions
        run: pnpm versions

      - name: Build app
        run: pnpm build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_uploader_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_uploader_secret_access_key }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync ./dist s3://$S3_FOR_FRONTEND/  --exclude '.git/*'
        env:
          S3_FOR_FRONTEND: ${{ secrets.s3_for_frontend }}

      - name: Delete cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_STATIC --paths "/*"
        env:
          CLOUDFRONT_STATIC: ${{ secrets.cloudfront_static }}
